import { useCallback, useEffect, useMemo, useState } from 'react';
import { FiPlus, FiSearch, FiTrash2 } from 'react-icons/fi';
import { toast } from 'react-toastify';
import api from '../../api/axios';
import useAuthStore from '../../context/storeAuth';

const emptyForm = { nombre: '', email: '', telefono: '', password: '', role: 'cliente' };
const Users = () => {
  const role = useAuthStore((state) => state.role);
  const currentUser = useAuthStore((state) => state.user);
  const [users, setUsers] = useState([]); const [search, setSearch] = useState(''); const [roleFilter, setRoleFilter] = useState(''); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState(emptyForm);
  const load = useCallback(async () => { try { const { data } = await api.get('/auth/users'); setUsers(data); } catch (error) { toast.error(error.response?.data?.mensaje || 'No se pudieron cargar los usuarios'); } }, []);
  useEffect(() => { if (role === 'administrador') load(); }, [load, role]);
  const filtered = useMemo(() => users.filter((user) => (!roleFilter || user.role === roleFilter) && (!search || `${user.nombre} ${user.email}`.toLowerCase().includes(search.toLowerCase()))), [users, search, roleFilter]);
  if (role !== 'administrador') return <div className="gc-card empty-state"><p>Este módulo es exclusivo para administradores.</p></div>;
  const patch = async (id, values) => { try { const { data } = await api.patch(`/auth/users/${id}`, values); setUsers((current) => current.map((user) => user._id === id ? data.user : user)); toast.success(data.mensaje); } catch (error) { toast.error(error.response?.data?.mensaje || 'No se pudo actualizar'); } };
  const remove = async (id) => { if (!window.confirm('¿Eliminar permanentemente este usuario?')) return; try { const { data } = await api.delete(`/auth/users/${id}`); setUsers((current) => current.filter((user) => user._id !== id)); toast.success(data.mensaje); } catch (error) { toast.error(error.response?.data?.mensaje || 'No se pudo eliminar'); } };
  const create = async (event) => { event.preventDefault(); try { const { data } = await api.post('/auth/users', form); setUsers((current) => [data.user, ...current]); setForm(emptyForm); setShowForm(false); toast.success(data.mensaje); } catch (error) { toast.error(error.response?.data?.mensaje || 'No se pudo crear'); } };
  return (
    <><header className="page-heading"><div><h2>Gestión de usuarios</h2><p>Crea cuentas, cambia roles, activa o desactiva accesos y administra el equipo.</p></div><button className="gc-button gc-button--primary" onClick={() => setShowForm((value) => !value)}><FiPlus /> Crear usuario</button></header>
      {showForm && <form className="gc-card gc-form" onSubmit={create} style={{ marginBottom: 20 }}><div className="form-row"><div className="form-field"><label>Nombre</label><input required value={form.nombre} onChange={(event) => setForm({ ...form, nombre: event.target.value })} /></div><div className="form-field"><label>Correo</label><input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></div></div><div className="form-row"><div className="form-field"><label>Teléfono</label><input required inputMode="numeric" value={form.telefono} onChange={(event) => setForm({ ...form, telefono: event.target.value })} /></div><div className="form-field"><label>Contraseña</label><input required type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></div></div><div className="form-field"><label>Rol</label><select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="cliente">Cliente</option><option value="repartidor">Repartidor</option><option value="administrador">Administrador</option></select></div><button className="gc-button gc-button--primary">Guardar usuario</button></form>}
      <div className="filter-bar"><div style={{ position: 'relative' }}><FiSearch style={{ position: 'absolute', left: 12, top: 13 }} /><input style={{ paddingLeft: 38 }} placeholder="Buscar usuario" value={search} onChange={(event) => setSearch(event.target.value)} /></div><select value={roleFilter} onChange={(event) => setRoleFilter(event.target.value)}><option value="">Todos los roles</option><option value="cliente">Cliente</option><option value="repartidor">Repartidor</option><option value="administrador">Administrador</option></select></div>
      <div className="gc-card table-wrap"><table className="gc-table"><thead><tr><th>Usuario</th><th>Rol</th><th>Confirmación</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{filtered.map((user) => <tr key={user._id}><td><div className="user-cell"><div className="user-cell__avatar">{user.avatar?.url ? <img src={user.avatar.url} alt="" /> : user.nombre?.[0]}</div><div><strong>{user.nombre}</strong><div className="form-help">{user.email}<br />{user.telefono}</div></div></div></td><td><select value={user.role} onChange={(event) => patch(user._id, { role: event.target.value })} disabled={user._id === currentUser?._id}><option value="cliente">Cliente</option><option value="repartidor">Repartidor</option><option value="administrador">Administrador</option></select></td><td>{user.emailConfirmed ? 'Confirmado' : <button className="gc-button gc-button--secondary gc-button--small" onClick={() => patch(user._id, { emailConfirmed: true })}>Confirmar</button>}</td><td><button className={`gc-button ${user.activo ? 'gc-button--success' : 'gc-button--ghost'} gc-button--small`} onClick={() => patch(user._id, { activo: !user.activo })} disabled={user._id === currentUser?._id}>{user.activo ? 'Activo' : 'Inactivo'}</button></td><td><button className="gc-button gc-button--danger gc-button--small" onClick={() => remove(user._id)} disabled={user._id === currentUser?._id}><FiTrash2 /></button></td></tr>)}</tbody></table></div>
    </>
  );
};
export default Users;
